version: "3.7"
services:
    app:
        build:
            args:
                user: dariush
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: oninesupport
        container_name: onineSupport-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - onineSupport

    db:
        image: mysql:5.7
        container_name: oninesupport-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - onineSupport

    nginx:
        image: nginx:alpine
        container_name: oninesupport-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - onineSupport

networks:
    onineSupport:
        driver: bridge
